[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "1.16.0"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
test_liquidation = "6qBNpKqHkGG5xMdJd2zivWMKn2Ym3sqjj4xbD2N13eyH"

[programs.devnet]
test_liquidation = "6qBNpKqHkGG5xMdJd2zivWMKn2Ym3sqjj4xbD2N13eyH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jnnj92/bot/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
